Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\auth-popup-image.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\example-remove-object.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\example-remove-people.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\example-swap-background-v2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\example-swap-background.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-1.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-2.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-3.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-beach-new.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-beach.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-plaza.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-people-remover-street.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-bg-1.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-bg-2.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-bg-3.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-object-1.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-object-2.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-object-3.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-text-paint.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-text-spring.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-text-tablet.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-remove-text-tshirt.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-replace-background-1.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-replace-background-2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-replace-background-3.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-replace-background-new-2.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-tiktok-remover-v2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-tiktok-remover.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale-1.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale-boat.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale-cat-new.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale-cat.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale-woman.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-upscale.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-watermark-remover-3.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\feature-watermark-remover.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\sora-page-man.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\sora-page-woman-v2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\sora-page-woman-v3.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\sora-page-woman-v4.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\sora-page-woman.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\video-page-red-panda.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\features\video-page-tiktok-girls.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\hero-comparison-v2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\hero-comparison.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-beach-woman.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-colosseum.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-field-man.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-field-woman.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-museum.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-station.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-street-man.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\people-remover-street-woman.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-beige.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-dark-blue.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-green.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-light-blue.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-lime.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-orange.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-pink.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\remove-text-yellow.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool1.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool3.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool4.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool5.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool6.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool7.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-page-tool8.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-1.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-3.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-4.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-5.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-6.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-7.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-8.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\sora-remover-9.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-auto-people-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-object-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-home.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-object.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-people-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-remove-bg-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-replace-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-text.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-upscaler-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-bg-video.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-home.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-object-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-people-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-remove-bg-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-replace-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-text.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-upscaler-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-remove-object-video.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-home.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-object.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-people-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-remove-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-replace-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-text.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-upscaler-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-replace-bg-video.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-text-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-upscaler-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\tool-card-video-page.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-bear.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-fox.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-lion.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-owl.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-panda.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-panther.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-penguin.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\upscaler-tiger.jpg" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-2.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-3.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-4.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-5.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-6.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-7.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-8.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\video-watermark-home.png" -Force
Remove-Item -Path "C:\Users\victo\Desktop\REMOVE WATER\public\images\tools\watermark-remover.png" -Force